# Generated by Django 2.2.7 on 2019-12-05 02:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_auto_20191204_1412'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='product',
            new_name='product_name',
        ),
    ]
