# Generated by Django 2.2.7 on 2019-11-25 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_contact_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='date',
            new_name='timestamp',
        ),
    ]
